contact_links:
  - name: âš™ï¸ Request a new plugin
    url: https://github.com/jigra-community/proposals
    about: Propose a new plugin or platform to the Jigra community
  - name: ğŸ™‹ Open a discussion
    url: https://github.com/navify/jigra/discussions
    about: Ask questions and discuss with other community members
